name: Docker

on:
  workflow_call: 
  
jobs:

  docker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.3.0

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: app_go

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: wevertonmatias
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: wevertonmatias/go_ci:${{ github.ref_name }}        
