name: Entrega contínua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: api_go
        
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        TARGET: /home/${{secrets.REMOTE_USER}}
        EXCLUDE: "postgres-data"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.REMOTE_HOST}}
        username: ${{secrets.REMOTE_USER}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
          export HOST=${{secrets.DBHOST}}
          export USER=${{secrets.DBUSER}}
          export PASSWORD=${{secrets.DBPASSWORD}}
          export DBNAME=${{secrets.DBNAME}}
          export PORT=${{secrets.DBPORT}}
          export PORT=8000
          chmod +x main
          nohup ./main > nohup.out 2> nohup.err < /dev/null &
