name: Entrega contínua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
  
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: api-go

    - uses: actions/checkout@v3
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        TARGET: /home/${{secrets.REMOTE_USER}}
        EXCLUDE: "/postgres-data"
