name: Entrega contínua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
  
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: api-go

    - uses: actions/checkout@v3
    
      
